[devshell]
name = "yctrl-dev-shell"

# packages = [ "cargo-watch" ]

[[commands]]
name = "yctrl"
help = "run main bin"
category = "Main"
command = "./result/bin/yctrl $@"

[[commands]]
name = "byctrl"
help = "build and run main bin"
category = "Main"
command = "nix run $@"

[[commands]]
name = "build"
help = "run nix build"
category = "Main"
command = "nix build $@"

[[commands]]
name = "watch"
help = "Startin cargo watch and do nix build"
category = "Main"
command = "cargo watch --clear --why --postpone --delay 5 --watch src --shell 'nix build'"
