name: "Build"

on:
  # Build on push to master
  push:
    branches:
      - master

  # Build on internal pull requests
  pull_request:

  # Allow to trigger for external PRs
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.7.0pre20220209_52f5231/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Building package
        run: nix build
